### ISSUE TITLE
Ftrack project prepare problem to create project default

### ISSUE THREAD

**Issue by jezscha** [pypeclub/pype#403]
**Describe the bug**
Ftrack project prepare problem to create project default once pype-config is having default.yaml with `root[work]` and root.json correctly set to have `root[work]`

```*** WRN: >>> { pypeapp.lib.anatomy }: [  Project "jtest02" does not have his own templates. Trying to use default.  ]
Traceback (most recent call last):
  File "C:\Users\jezsc\CODE\pype-setup\vendor\python\ftrack-python-api\ftrack_api\event\hub.py", line 710, in _handle
    response = subscriber.callback(event)
  File "C:\Users\jezsc\CODE\pype-setup\repos\pype\pype\modules\ftrack\lib\ftrack_action_handler.py", line 155, in _launch
    self.session, entities, event
  File "C:\Users\jezsc\CODE\pype-setup\repos\pype\pype\modules\ftrack\lib\ftrack_action_handler.py", line 107, in _interface
    interface = self.interface(session, entities, event)
  File "C:\Users\jezsc\CODE\pype-setup/repos/pype/pype/modules/ftrack/actions\action_prepare_project.py", line 63, in interface
    root_items = self.prepare_root_items(anatomy)
  File "C:\Users\jezsc\CODE\pype-setup/repos/pype/pype/modules/ftrack/actions\action_prepare_project.py", line 123, in prepare_root_items
    root_names = anatomy.root_names()
  File "C:\Users\jezsc\CODE\pype-setup\pypeapp\lib\anatomy.py", line 157, in root_names
    return self.root_names_from_templates(self.templates)
  File "C:\Users\jezsc\CODE\pype-setup\pypeapp\lib\anatomy.py", line 219, in root_names_from_templates
    raise RootCombinationError(roots)
pypeapp.lib.anatomy.RootCombinationError: Combination of root with and without root name in Templates. "root[renders]", "root[work]", "root", "root[publish]", "root[production]"
```

**To Reproduce**
1. set your pype-config/anatomy/default.yaml to be pointing to individual roots like for example `root[work]`, `root[render]`
2. define correct paths in root.json to host pointers for `root[work]`, `root[render]`
3. then create new project in ftrack and run Project prepare action on it
4. it should be returning error in terminal

**Comment by mkolar** [comment]
this was caused by a wrong combination of anatomy (using simple root) and multiroot setup. We'll be doing more checks in 3.0 settings to is becoming irrelevant.
