### ISSUE TITLE
Ftrack to Avalon bug

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/pype#406]
```
An error occurred during synchronization
Traceback of the error
Traceback (most recent call last):
File "C:\Users\admin\bumpybox_development\pype-setup/repos/pype/pype/modules/ftrack/actions\action_sync_to_avalon.py", line 76, in launch
self.entities_factory.set_cutom_attributes()
File "C:\Users\admin\bumpybox_development\pype-setup\repos\pype\pype\modules\ftrack\lib\avalon_sync.py", line 808, in set_cutom_attributes
[values] = self.session.call(call_expr)
File "C:\Users\admin\bumpybox_development\pype-setup\vendor\python\ftrack-python-api\ftrack_api\session.py", line 1638, in call
raise ftrack_api.exception.ServerError(error_message)
ftrack_api.exception.ServerError: Server reported error: ParseError(Failed to parse: select value, entity_id from ContextCustomAttributeValue where entity_id in ("04189a2e-517e-11ea-8b4e-c647b6061ecb", "df9d5720-32f1-11ea-b537-d6f29b8fd76c", "0620bb02-33b6-11ea-afc7-d6f29b8fd76c", "2c149578-32f2-11ea-bad2-d6f29b8fd76c", "0aa232d8-84a5-11ea-8b73-deba72931832", "1e03ab78-51a0-11ea-996f-c647b6061ecb", "9adcc302-84a2-11ea-b6a1-deba72931832", "130f19d6-84a5-11ea-975d-deba72931832", "1864e97e-33ce-11ea-b537-d6f29b8fd76c", "2b6f004a-84a5-11ea-975d-deba72931832", "195f0e48-84a2-11ea-8b73-deba72931832", "ca37e5b0-5198-11ea-81d4-c647b6061ecb", "d9a358d0-62c4-11ea-baf9-c647b6061ecb", "1aa7706c-84a5-11ea-b009-deba72931832", "fe4911ba-5195-11ea-81d4-c647b6061ecb", "20ba28dc-84a5-11ea-92f4-deba72931832", "21bf43dc-84a2-11ea-af27-deba72931832", "235a8b3a-69cb-11ea-9014-9625801d0ef6", "a81bf3fc-4376-11ea-b938-c647b6061ecb", "264db12e-84a5-11ea-95bf-deba72931832", "2a8748b2-84a1-11ea-9b00-deba72931832", "e5f7d95c-5195-11ea-81d4-c647b6061ecb", "2dcf007c-84a2-11ea-92f4-deba72931832", "30b5a5f4-84a5-11ea-8b73-deba72931832", "3133aaca-84a1-11ea-9707-deba72931832", "3369c9de-51a0-11ea-8303-c647b6061ecb", "39321b8c-51a0-11ea-83c6-c647b6061ecb", "465bc708-517e-11ea-b747-c647b6061ecb", "4dbf759e-517e-11ea-81d4-c647b6061ecb", "e7b4c338-84a1-11ea-b009-deba72931832", "5ec63676-51a5-11ea-996f-c647b6061ecb", "8bed7af8-84a2-11ea-b6a1-deba72931832", "864b3536-84a2-11ea-9707-deba72931832", "8e9282ca-84a3-11ea-9b00-deba72931832", "90dd4d18-84a2-11ea-af27-deba72931832", "a277ff7e-62f0-11ea-bb93-c647b6061ecb", "b5de9774-4376-11ea-9564-c647b6061ecb", "e156a358-84a1-11ea-95bf-deba72931832") and configuration_id in (). Expected end of text (at char 1568), (line:1, col:1569))
````

**Comment by tokejepsen** [comment]
Fixed by running "Create/Update Attributes"
